name: PR Comment Deploy Trigger

on:
  issue_comment:
    types: [created]

jobs:
  check-comment:
    if: ${{ github.event.issue.pull_request }} # Ensure it runs only on PR comments
    runs-on: ubuntu-latest

    steps:
      - name: Check comment body
        if: contains(github.event.comment.body, '.deploy')
        run: echo "Deployment comment detected in PR: ${GITHUB_EVENT_PATH}"