name: Check Even Minute on PR Approval

on:
  pull_request_target:
    types: [labeled]

jobs:
  check-even-minute:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check even minute
        run: |
          for i in {1..10}
          do
            current_minute=$(date +'%M')
            if [ $((10#$current_minute % 2)) -eq 0 ]; then
              echo "The current minute ($current_minute) is even."
              break
            else
              echo "The current minute ($current_minute) is odd."
            fi
            sleep 10
          done