name: PR Comment Deploy Trigger

on:
  issue_comment:
    types: [created]

jobs:
  check-comment:
    if: ${{ github.event.issue.pull_request }} # Ensure it runs only on PR comments
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print comment body
        run: echo "Comment body: ${{ github.event.comment.body }}"

      - name: Check for deployment comment
        if: contains(github.event.comment.body, '.deploy')
        run: echo "Deployment comment detected in PR: ${{ github.event.issue.number }}"
