name: CI Approval and Merge

on:
  pull_request_target:
    types: [labeled]

jobs:
  check-even-minute-and-merge:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'ci'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Authenticate with GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo "${{ secrets.GH_TOKEN }}" | gh auth login --with-token

      - name: Check even minute and merge PR
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          for i in {1..10}
          do
            current_minute=$(date +'%M')
            if [ $((10#$current_minute % 2)) -eq 0 ]; then
              echo "The current minute ($current_minute) is even."
              echo "Waiting for 10 more seconds..."
              sleep 10
              gh pr merge $PR_NUMBER --merge --admin
              break
            else
              echo "The current minute ($current_minute) is odd."
            fi
            sleep 60
          done